{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "name" : "categories",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 9. The following are available: 04ccf63925272a44 (6.0.1)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'WS-AMRKA', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'\nDriver info: driver.version: AndroidDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to find an active device or emulator with OS 9. The following are available: 04ccf63925272a44 (6.0.1)\n    at getResponseForW3CError (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)\n    at <anonymous>\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'WS-AMRKA', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'\nDriver info: driver.version: AndroidDriver",
      "children" : [ {
        "name" : "setUp",
        "uid" : "cd82314ad51c0c63",
        "parentUid" : "2cc7ceb99fdecb40a2fed8b3b95e31c6",
        "status" : "broken",
        "time" : {
          "start" : 1573055233042,
          "stop" : 1573055233043,
          "duration" : 1
        },
        "flaky" : true,
        "parameters" : [ "4723", "mdf", "100", "mdf:5050", "SM-G950F", "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note5.json", "9", "8200", "RF8M82EDL8Y", "8240" ]
      } ],
      "uid" : "2cc7ceb99fdecb40a2fed8b3b95e31c6"
    }, {
      "name" : "java.lang.NullPointerException",
      "children" : [ {
        "name" : "cleanUp",
        "uid" : "e1b8b3d07412c62a",
        "parentUid" : "5592898b36d684905e31486a23088bda",
        "status" : "broken",
        "time" : {
          "start" : 1573055233114,
          "stop" : 1573055233114,
          "duration" : 0
        },
        "flaky" : true,
        "parameters" : [ "4723", "mdf", "100", "mdf:5050", "SM-G950F", "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note5.json", "9", "8200", "RF8M82EDL8Y", "8240" ]
      }, {
        "name" : "cleanUp",
        "uid" : "52f6a2a739e9f536",
        "parentUid" : "5592898b36d684905e31486a23088bda",
        "status" : "broken",
        "time" : {
          "start" : 1573670831658,
          "stop" : 1573670831659,
          "duration" : 1
        },
        "flaky" : true,
        "parameters" : [ "4723", "mdf", "100", "mdf:5050", "Nexus 5", "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note5.json", "6.0.1", "8200", "RF8M82EDL8Y", "8240" ]
      } ],
      "uid" : "5592898b36d684905e31486a23088bda"
    }, {
      "name" : "Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. \nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'WS-AMRKA', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'\nDriver info: driver.version: AndroidDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: The instrumentation process cannot be initialized within 30000ms timeout. Make sure the application under test does not crash and investigate the logcat output. You could also try to increase the value of 'uiautomator2ServerLaunchTimeout' capability. \n    at getResponseForW3CError (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/home/linuxbrew/.linuxbrew/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:388:37)\n    at <anonymous>\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'WS-AMRKA', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231'\nDriver info: driver.version: AndroidDriver",
      "children" : [ {
        "name" : "setUp",
        "uid" : "fd24c52471903154",
        "parentUid" : "5a13ebc854a4df9c92b3d26b6c6581e0",
        "status" : "broken",
        "time" : {
          "start" : 1574455921697,
          "stop" : 1574455921697,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "4723", "mdf", "100", "mdf:5050", "Nexus 5", "/Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/selenium/note5.json", "6.0.1", "8200", "RF8M82EDL8Y", "8240" ]
      } ],
      "uid" : "5a13ebc854a4df9c92b3d26b6c6581e0"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ]
}